name: Joes Scout Spot
favicon: null
layout_spectrum: 0.7480306909419596
typography_spectrum: 0.24142
title: For all thing Scouting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#193c8d'
    - '#00bbe6'
    - '#aebbd1'
    - '#6e7aa2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
