name: Joes Scout Spot
favicon: null
layout_spectrum: 0.7480306909419596
typography_spectrum: 0.9400097068864852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.44980374444276094
  lightness: 0.12707564025186002
  saturation: 0.28952316334471107
  rhythmicContrast: 0.08531715255230665
purpose: []
