name: Joes Scout Spot
favicon: null
layout_spectrum: 0.7480306909419596
typography_spectrum: 0.9400097068864852
title: For all thing Scouting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0b0c'
    - '#ff0000'
    - '#f0debe'
    - '#744c41'
    - '#0058a9'
  brandStrength: 0.44980374444276094
  lightness: 0.5
  saturation: 0.28952316334471107
  rhythmicContrast: 0.08531715255230665
purpose: []
